language: groovy
before_install:
 - chmod +x gradlew
install: ./gradlew resolveAllDependencies assemble
script: ./gradlew clean build
notifications:
  email: false
branches:
  only:
    - transition
env:
  global:
  - TERM=dumb
